export const TIME_DIFFICULTY_CURVE = {
  fastRampStartSeconds: 24,
  earlyDifficultyPerSecond: 0.02,
  lateDifficultyPerSecond: 0.07,
  earlySpeedPerSecond: 4.2,
  lateSpeedPerSecond: 11.5,
  earlyEnemyPerSecond: 0.007,
  lateEnemyPerSecond: 0.025,
  earlyGapPerSecond: 1.9,
  lateGapPerSecond: 5.7,
  earlyPlatformShrinkPerSecond: 1.5,
  latePlatformShrinkPerSecond: 4.2,
  earlyVerticalPerSecond: 1.2,
  lateVerticalPerSecond: 3.8,
  maxDifficultyBonus: 2.1,
  maxSpeedBonus: 440,
  maxEnemyBonus: 0.92,
  maxGapBonus: 230,
  maxPlatformShrink: 170,
  maxVerticalBonus: 140,
};
