export const TIME_DIFFICULTY_CURVE = {
  fastRampStartSeconds: 18,
  earlyDifficultyPerSecond: 0.038,
  lateDifficultyPerSecond: 0.12,
  earlySpeedPerSecond: 8.5,
  lateSpeedPerSecond: 20,
  earlyEnemyPerSecond: 0.012,
  lateEnemyPerSecond: 0.04,
  earlyGapPerSecond: 3.6,
  lateGapPerSecond: 10,
  earlyPlatformShrinkPerSecond: 2.8,
  latePlatformShrinkPerSecond: 7.6,
  earlyVerticalPerSecond: 2.4,
  lateVerticalPerSecond: 6.8,
  maxDifficultyBonus: 3.4,
  maxSpeedBonus: 720,
  maxEnemyBonus: 1.45,
  maxGapBonus: 390,
  maxPlatformShrink: 260,
  maxVerticalBonus: 230,
};
